version: '3'

services:
  web:
    image: 'nginx:latest'
    ports:
      - 9000:80
    volumes:
      - ./conf.d:/etc/nginx/conf.d
      - ./app:/app
    links:
      - php
  
  php:
    image: 'php:7-fpm'
    volumes:
      - ./app:/app
