apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  labels:
    app: wordpress
spec:
  storageClassName: my-local-storage 
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
