apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress-resource
spec:
  rules:
  - host: ec2-3-92-207-163.compute-1.amazonaws.com
    http:
      paths:
      - backend:
          serviceName: wordpress 
          servicePort: 80
