---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  default.conf: |-
     server {
      listen 80 default_server;
      error_log  /var/log/nginx/error.log;
      access_log /var/log/nginx/access.log;
      root /var/www/html;
      server_name _;
 
      location / {
      try_files $uri $uri/index.php;
      }

      location ~ \.php$ {
      fastcgi_split_path_info ^(.+\.php)(/.+)$;
      fastcgi_pass localhost:9000;
      fastcgi_index index.php;
      include fastcgi_params;
      fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
      fastcgi_param PATH_INFO $fastcgi_path_info;
      #include fastcgi_params;
      #fastcgi_param REQUEST_METHOD $request_method;
      #fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
      #fastcgi_pass 127.0.0.1:9000;
        }
     }
